SELECT a.SERIAL_NUM,ct,PART_NUM,PASS_FAIL,SYSTEM_ID,STEP_NAME, CARRIER_SERIAL_NUM,PROCESS_NAME, START_DATE, END_DATE ,
 (END_DATE - START_DATE) *1440 CYCLE_TIME,  

CASE WHEN (END_DATE - START_DATE) *1440 > 50 THEN 'HIGH CYCLE TIME'
ELSE 'OK CYCLE TIME'
END CT_STATUS

  FROM 

(SELECT ROWNUM RENGLON,SERIAL_NUM,cycle_time/60 ct,PART_NUM,PASS_FAIL,SYSTEM_ID, PROCESS_DATE END_DATE,STEP_NAME, CARRIER_SERIAL_NUM,PROCESS_NAME 
FROM 
    (SELECT * FROM LR4_SHIM_ASSEMBLY
    WHERE process_date >= sysdate - 0.3
    AND system_id = 'CYBOND57'
    ORDER BY process_date)
) a, 

(SELECT ROWNUM+1 RENGLON,SERIAL_NUM,PROCESS_DATE START_DATE FROM 
    (SELECT * FROM LR4_SHIM_ASSEMBLY
    WHERE process_date >= sysdate - 0.3
    AND system_id = 'CYBOND56'
    ORDER BY process_date)
) b

WHERE A.RENGLON = B.RENGLON 

 